name: Update Datetime File

on:
  push:
    branches:
      - abhishek_GithubAction

jobs:
  update-datetime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (optional, only if needed for your setup)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run the script
        run: |
        
          if [[ "$COMMIT_MESSAGE" == *"RunAction"* ]]; then
            echo "Commit message contains 'RunAction'."
            chmod +x ./create_datetime_file.sh
            ./create_datetime_file.sh
          else
            echo "Commit message does not contain 'RunAction'."
            echo "run_action=false" >> $GITHUB_ENV
            exit 0
          fi
