name: Update Datetime File

on:
  push:
    branches:
      - abhishek_GithubAction

jobs:
  update-datetime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (optional, only if needed for your setup)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run the script
        run: |

          sudo apt-get update -y
          sudo apt-get install -y build-essential pkg-config libsodium-dev libssl-dev libzmq3-dev
          sudo snap install --edge --classic just

          #xcode-select --install
          #cargo install cargo-lipo
        
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MESSAGE" == *"RunAction"* ]]; then
            echo "Commit message contains 'RunAction'."
            chmod +x ./aries/wrappers/uniffi-aries-vcx/scripts/ios.build.cargo.sh
            ./aries/wrappers/uniffi-aries-vcx/scripts/ios.build.cargo.sh
            chmod +x ./create_datetime_file.sh
            ./create_datetime_file.sh
          else
            echo "Commit message does not contain 'RunAction'."
            exit 0
          fi
